export const RESET_AUTH = 'RESET_AUTH'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const GETSETTINGS_SUCCESS = 'GETSETTINGS_SUCCESS';
export const GETSETTINGS_FAIL = 'GETSETTINGS_FAIL';

export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS';
export const FORGET_PASSWORD_FAIL = 'FORGET_PASSWORD_FAIL';

export const OTP_SUCCESS = 'OTP_SUCCESS';
export const OTP_FAIL = 'OTP_FAIL';

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';


export const COUNTRY_SUCCESS = 'COUNTRY_SUCCESS';
export const COUNTRY_FAIL = 'COUNTRY_FAIL';

export const SET_ACTIVE_COUNTRY = 'SET_ACTIVE_COUNTRY';


export const AUTH_INPUT = 'AUTH_INPUT';
export const LOGOUT = 'LOGOUT';

export const RESET_USER = 'RESET_USER'




