export const LOAD_PRODUCT_SUCCESS = 'LOAD_PRODUCT_SUCCESS';
export const LOAD_PRODUCT_FAIL = 'LOAD_PRODUCT_FAIL';

export const CART_ITEMCOUNT_SUCCESS = 'CART_ITEMCOUNT_SUCCESS';
export const CART_ITEMCOUNT_FAIL = 'CART_ITEMCOUNT_FAIL';

export const PET_ADDTOCART_SUCCESS = 'PET_ADDTOCART_SUCCESS';
export const PET_ADDTOCART_FAIL = 'PET_ADDTOCART_FAIL';

export const ACCESSORIES_ADDTOCART_SUCCESS = 'ACCESSORIES_ADDTOCART_SUCCESS';
export const ACCESSORIES_ADDTOCART_FAIL = 'ACCESSORIES_ADDTOCART_FAIL';

export const UPDATE_CARTITEM_SUCCESS = 'UPDATE_CARTITEM_SUCCESS';
export const UPDATE_CARTITEM_FAIL = 'UPDATE_CARTITEM_FAIL';

export const ITEM_DELETE_SUCCESS = 'ITEM_DELETE_SUCCESS';
export const ITEM_DELETE_FAIL = 'ITEM_DELETE_FAIL';

//PAYMENT- HYPER PAY

export const DIRECT_BUY_RESULT_SUCCESS = 'DIRECT_BUY_RESULT_SUCCESS';
export const DIRECT_BUY_RESULT_FAIL = 'DIRECT_BUY_RESULT_FAIL';

export const CART_CHECKOUT_PAYMENT_SUCCESS = 'CART_CHECKOUT_PAYMENT_SUCCESS';
export const CART_CHECKOUT_PAYMENT_FAIL = 'CART_CHECKOUT_PAYMENT_FAIL';

export const CART_CHECKOUT_RESULT_SUCCESS = 'CART_CHECKOUT_RESULT_SUCCESS';
export const CART_CHECKOUT_RESULT_FAIL = 'CART_CHECKOUT_RESULT_FAIL';

export const MEMSHIP_BUY_PAYMENT_SUCCESS = 'MEMSHIP_BUY_PAYMENT_SUCCESS';
export const MEMSHIP_BUY_PAYMENT_FAIL = 'MEMSHIP_BUY_PAYMENT_FAIL';

export const MEMSHIP_BUY_RESULT_SUCCESS = 'MEMSHIP_BUY_RESULT_SUCCESS';
export const MEMSHIP_BUY_RESULT_FAIL = 'MEMSHIP_BUY_RESULT_FAIL';

export const PRODUCT_FEEDBACK_SUCCESS = 'PRODUCT_FEEDBACK_SUCCESS'
export const PRODUCT_FEEDBACK_FAIL = 'PRODUCT_FEEDBACK_FAIL'

export const CART_INPUT = 'CART_INPUT'

export const UPDATE_CART = 'UPDATE_CART'
