export const CHATTED_USERLIST_SUCCESS = 'CHATTED_USERLIST_SUCCESS';
export const CHATTED_USERLIST_FAIL = 'CHATTED_USERLIST_FAIL';

export const TWOUSER_CHATLIST_SUCCESS = 'TWOUSER_CHATLIST_SUCCESS';
export const TWOUSER_CHATLIST_FAIL = 'TWOUSER_CHATLIST_FAIL';

export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL';

export const CONVERSATN_OPPONENT_LIST_SUCCESS = 'CONVERSATN_OPPONENT_LIST_SUCCESS';
export const CONVERSATN_OPPONENT_LIST_FAIL = 'CONVERSATN_OPPONENT_LIST_FAIL';

export const CONVERSATN_CHAT_HISTORY_SUCCESS = 'CONVERSATN_CHAT_HISTORY_SUCCESS';
export const CONVERSATN_CHAT_HISTORY_FAIL = 'CONVERSATN_CHAT_HISTORY_FAIL';

export const STARTCHAT_PRODUCT_DETAILS_SUCCESS = 'STARTCHAT_PRODUCT_DETAILS_SUCCESS';
export const STARTCHAT_PRODUCT_DETAILS_FAIL = 'STARTCHAT_PRODUCT_DETAILS_FAIL';

export const CREATE_FIRSTCHAT_SUCCESS = 'CREATE_FIRSTCHAT_SUCCESS';
export const CREATE_FIRSTCHAT_FAIL = 'CREATE_FIRSTCHAT_FAIL';

export const INBOX_CONTINUE_CHAT_SUCCESS = 'INBOX_CONTINUE_CHAT_SUCCESS';
export const INBOX_CONTINUE_CHAT_FAIL = 'INBOX_CONTINUE_CHAT_FAIL';
