export const LOADING = 'LOADING';
export const RESET_ERROR = 'RESET_ERROR';
export const RESET_PRODUCT = 'RESET_PRODUCT';


export const MYZOO_PICKS_SUCCESS = 'MYZOO_PICKS_SUCCESS';
export const MYZOO_PICKS_FAIL = 'MYZOO_PICKS_FAIL';

export const MYZOOPICKS_PRODUCT_SUCCESS = 'MYZOOPICKS_PRODUCT_SUCCESS';
export const MYZOOPICKS_PRODUCT_FAIL = 'MYZOOPICKS_PRODUCT_FAIL';

export const PRODUCT_BYID_SUCCESS = 'PRODUCT_BYID_SUCCESS';
export const PRODUCT_BYID_FAIL = 'PRODUCT_BYID_FAIL';

export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const SET_ACTIVE_ITEM = 'SET_ACTIVE_ITEM';

export const LATEST_PETS_SUCCESS = 'LATEST_PETS_SUCCESS';
export const LATEST_PETS_FAIL = 'LATEST_PETS_FAIL';

export const LATEST_ACCESSORIES_SUCCESS = 'LATEST_ACCESSORIES_SUCCESS';
export const LATEST_ACCESSORIES_FAIL = 'LATEST_ACCESSORIES_FAIL';

export const LATEST_SERVICES_SUCCESS = 'LATEST_SERVICES_SUCCESS';
export const LATEST_SERVICES_FAIL = 'LATEST_SERVICES_FAIL';

export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL';

export const SUBCATEGORY_LIST_SUCCESS = 'SUBCATEGORY_LIST_SUCCESS';
export const SUBCATEGORY_LIST_FAIL = 'SUBCATEGORY_LIST_FAIL';

export const RECENT_POST_SUCCESS = 'RECENT_POST_SUCCESS';
export const RECENT_POST_FAIL = 'RECENT_POST_FAIL';


export const SERVICES_SUCCESS = 'SERVICES_SUCCESS';
export const SERVICES_FAIL = 'SERVICES_FAIL';

export const HOME_INPUT = 'HOME_INPUT'

export const EVERY_RANGE_SUCCESS = 'EVERY_RANGE_SUCCESS';
export const EVERY_RANGE_FAIL = 'EVERY_RANGE_FAIL';

export const FAVOURITE_ARRAY = 'FAVOURITE_ARRAY'

