export const RESET_ITEM = 'RESET_ITEM';

export const SET_ACTIVE_CURRENCY = 'SET_ACTIVE_CURRENCY';

export const MEMBERSHIP_LIST_SUCCESS = 'MEMBERSHIP_LIST_SUCCESS';
export const MEMBERSHIP_LIST_FAIL = 'MEMBERSHIP_LIST_FAIL';

export const ADD_WISHLIST_SUCCESS = 'ADD_WISHLIST_SUCCESS';
export const ADD_WISHLIST_FAIL = 'ADD_WISHLIST_FAIL';

export const DELETE_WISHLIST_SUCCESS = 'DELETE_WISHLIST_SUCCESS';
export const DELETE_WISHLIST_FAIL = 'DELETE_WISHLIST_FAIL';

export const WISHLIST_SUCCESS = 'WISHLIST_SUCCESS';
export const WISHLIST_FAIL = 'WISHLIST_FAIL';

export const ADD_FAVOURITE_SUCCESS = 'ADD_FAVOURITE_SUCCESS';
export const ADD_FAVOURITE_FAIL = 'ADD_FAVOURITE_FAIL';

export const DELETE_FAVOURITE_SUCCESS = 'DELETE_FAVOURITE_SUCCESS';
export const DELETE_FAVOURITE_FAIL = 'DELETE_FAVOURITE_FAIL';

export const MY_FAVOURITE_SUCCESS = 'MY_FAVOURITE_SUCCESS';
export const MY_FAVOURITE_FAIL = 'MY_FAVOURITE_FAIL';

export const CHANGE_ITEM_STATUS_SUCCESS = 'CHANGE_ITEM_STATUS_SUCCESS';
export const CHANGE_ITEM_STATUS_FAIL = 'CHANGE_ITEM_STATUS_FAIL';

export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_FAIL = 'DELETE_ITEM_FAIL';

export const EDIT_ITEM_SUCCESS = 'EDIT_ITEM_SUCCESS';
export const EDIT_ITEM_FAIL = 'EDIT_ITEM_FAIL';

export const MY_ITEM_LIST_SUCCESS = 'MY_ITEM_LIST_SUCCESS';
export const MY_ITEM_LIST_FAIL = 'MY_ITEM_LIST_FAIL';

export const ADD_COMPARE_LIST_SUCCESS = 'ADD_COMPARE_LIST_SUCCESS';
export const ADD_COMPARE_LIST_FAIL = 'ADD_COMPARE_LIST_FAIL';

export const DELETE_COMPARE_LIST_SUCCESS = 'DELETE_COMPARE_LIST_SUCCESS';
export const DELETE_COMPARE_LIST_FAIL = 'DELETE_COMPARE_LIST_FAIL';

export const COMPARE_LIST_SUCCESS = 'COMPARE_LIST_SUCCESS';
export const COMPARE_LIST_FAIL = 'COMPARE_LIST_FAIL';

export const MY_BIDDING_SUCCESS = 'MY_BIDDING_SUCCESS';
export const MY_BIDDING_FAIL = 'MY_BIDDING_FAIL';

export const LAST_BIDDING_AMOUNT_SUCCESS = 'LAST_BIDDING_AMOUNT_SUCCESS';
export const LAST_BIDDING_AMOUNT_FAIL = 'LAST_BIDDING_AMOUNT_FAIL';

export const BIDDERS_LIST_SUCCESS = 'BIDDERS_LIST_SUCCESS';
export const BIDDERS_LIST_FAIL = 'BIDDERS_LIST_FAIL';

export const SUBMIT_BID_SUCCESS = 'SUBMIT_BID_SUCCESS';
export const SUBMIT_BID_FAIL = 'SUBMIT_BID_FAIL';

export const FILTER_ITEM_SUCCESS = 'FILTER_ITEM_SUCCESS';
export const FILTER_ITEM_FAIL = 'FILTER_ITEM_FAIL';

export const AGE_TYPE_LIST_SUCCESS = 'AGE_TYPE_LIST_SUCCESS';
export const AGE_TYPE_LIST_FAIL = 'AGE_TYPE_LIST_FAIL';

export const SIZE_TYPE_LIST_SUCCESS = 'SIZE_TYPE_LIST_SUCCESS';
export const SIZE_TYPE_LIST_FAIL = 'SIZE_TYPE_LIST_FAIL';

export const WEIGHT_TYPE_LIST_SUCCESS = 'WEIGHT_TYPE_LIST_SUCCESS';
export const WEIGHT_TYPE_LIST_FAIL = 'WEIGHT_TYPE_LIST_FAIL';

export const EVERY_RANGES_SUCCESS = 'EVERY_RANGES_SUCCESS';
export const EVERY_RANGES_FAIL = 'EVERY_RANGES_FAIL';

export const CURRENCY_SUCCESS = 'CURRENCY_SUCCESS';
export const CURRENCY_FAIL = 'CURRENCY_FAIL';

export const CURRENCY_CHANGE_SUCCESS = 'CURRENCY_CHANGE_SUCCESS';
export const CURRENCY_CHANGE_FAIL = 'CURRENCY_CHANGE_FAIL';

export const SERVICE_MEMSHP_PLANCHECK_SUCCESS = 'SERVICE_MEMSHP_PLANCHECK_SUCCESS';
export const SERVICE_MEMSHP_PLANCHECK_FAIL = 'SERVICE_MEMSHP_PLANCHECK_FAIL';

export const ACCESSORIES_MEMSHP_PLANCHECK_SUCCESS = 'ACCESSORIES_MEMSHP_PLANCHECK_SUCCESS';
export const ACCESSORIES_MEMSHP_PLANCHECK_FAIL = 'ACCESSORIES_MEMSHP_PLANCHECK_FAIL';

export const PET_MEMSHP_PLANCHECK_SUCCESS = 'PET_MEMSHP_PLANCHECK_SUCCESS';
export const PET_MEMSHP_PLANCHECK_FAIL = 'PET_MEMSHP_PLANCHECK_FAIL';

export const PET_SAVE_SUCCESS = 'PET_SAVE_SUCCESS';
export const PET_SAVE_FAIL = 'PET_SAVE_FAIL';

export const ACCESSORIES_SAVE_SUCCESS = 'ACCESSORIES_SAVE_SUCCESS';
export const ACCESSORIES_SAVE_FAIL = 'ACCESSORIES_SAVE_FAIL';

export const ADD_SERVICE_SUCCESS = 'ADD_SERVICE_SUCCESS';
export const ADD_SERVICE_FAIL = 'ADD_SERVICE_FAIL';

export const EDIT_PET_DETAILS_SUCCESS = 'EDIT_PET_DETAILS_SUCCESS';
export const EDIT_PET_DETAILS_FAIL = 'EDIT_PET_DETAILS_FAIL';

export const EDIT_ACCESSORIES_DETAILS_SUCCESS = 'EDIT_ACCESSORIES_DETAILS_SUCCESS';
export const EDIT_ACCESSORIES_DETAILS_FAIL = 'EDIT_ACCESSORIES_DETAILS_FAIL';

export const EDIT_SERVICE_DETAILS_SUCCESS = 'EDIT_SERVICE_DETAILS_SUCCESS';
export const EDIT_SERVICE_DETAILS_FAIL = 'EDIT_SERVICE_DETAILS_FAIL';

export const LOADING = 'LOADING';
