export const RESET_FEEDBACK = 'RESET_FEEDBACK';

export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';

export const ORDERED_PRODUCT_SUCCESS = 'ORDERED_PRODUCT_SUCCESS';
export const ORDERED_PRODUCT_FAIL = 'ORDERED_PRODUCT_FAIL';

export const SELLER_FEEDBACK_SUCCESS = 'SELLER_FEEDBACK_SUCCESS';
export const SELLER_FEEDBACK_FAIL = 'SELLER_FEEDBACK_FAIL';

export const DELIVERY_FEEDBACK_SUCCESS = 'DELIVERY_FEEDBACK_SUCCESS';
export const DELIVERY_FEEDBACK_FAIL = 'DELIVERY_FEEDBACK_FAIL';

export const WRITE_REVIEW_SUCCESS = 'WRITE_REVIEW_SUCCESS';
export const WRITE_REVIEW_FAIL = 'WRITE_REVIEW_FAIL';

export const REQUEST_RETURN_SUCCESS = 'REQUEST_RETURN_SUCCESS';
export const REQUEST_RETURN_FAIL = 'REQUEST_RETURN_FAIL';

export const ORDER_STATUS_SUCCESS = 'ORDER_STATUS_SUCCESS';
export const ORDER_STATUS_FAIL = 'ORDER_STATUS_FAIL';

export const SELLER_DETAILS_SUCCESS = 'SELLER_DETAILS_SUCCESS';
export const SELLER_DETAILS_FAIL = 'SELLER_DETAILS_FAIL';

export const SELLER_PRODUCTS_SUCCESS = 'SELLER_PRODUCTS_SUCCESS';
export const SELLER_PRODUCTS_FAIL = 'SELLER_PRODUCTS_FAIL';

export const SELLER_RATINGS_SUCCESS = 'SELLER_RATINGS_SUCCESS';
export const SELLER_RATINGS_FAIL = 'SELLER_RATINGS_FAIL';

export const SELLER_RATINGS_REPLAY_SUCCESS = 'SELLER_RATINGS_REPLAY_SUCCESS';
export const SELLER_RATINGS_REPLAY_FAIL = 'SELLER_RATINGS_REPLAY_FAIL';

export const SELLER_RATINGS_COUNT_SUCCESS = 'SELLER_RATINGS_COUNT_SUCCESS';
export const SELLER_RATINGS_COUNT_FAIL = 'SELLER_RATINGS_COUNT_FAIL';

export const SAVE_SELLER_RATINGS_SUCCESS = 'SAVE_SELLER_RATINGS_SUCCESS';
export const SAVE_SELLER_RATINGS_FAIL = 'SAVE_SELLER_RATINGS_FAIL';

export const SAVE_REPLAY_COMPANY_RATINGS_SUCCESS = 'SAVE_REPLAY_COMPANY_RATINGS_SUCCESS';
export const SAVE_REPLAY_COMPANY_RATINGS_FAIL = 'SAVE_REPLAY_COMPANY_RATINGS_FAIL';

export const SET_ACTIVE_ORDER = 'SET_ACTIVE_ORDER';


