export const ABOUT_US_SUCCESS = 'ABOUT_US_SUCCESS';
export const ABOUT_US_FAIL = 'ABOUT_US_FAIL';

export const FAQS_SUCCESS = 'FAQS_SUCCESS';
export const FAQS_FAIL = 'FAQS_FAIL';

export const PRIVACY_POLICY_SUCCESS = 'PRIVACY_POLICY_SUCCESS';
export const PRIVACY_POLICY_FAIL = 'PRIVACY_POLICY_FAIL';

export const CONTACT_US_SUCCESS = 'CONTACT_US_SUCCESS';
export const CONTACT_US_FAIL = 'CONTACT_US_FAIL';

export const RESET = 'RESET';

export const UPDATE_ADDRESS_SUCCESS = 'UPDATE_ADDRESS_SUCCESS';
export const UPDATE_ADDRESS_FAIL = 'UPDATE_ADDRESS_FAIL';

export const MAKE_DEFAULT_ADDRESS_SUCCESS = 'MAKE_DEFAULT_ADDRESS_SUCCESS';
export const MAKE_DEFAULT_ADDRESS_FAIL = 'MAKE_DEFAULT_ADDRESS_FAIL';

export const DELETE_ADDRESS_SUCCESS = 'DELETE_ADDRESS_SUCCESS';
export const DELETE_ADDRESS_FAIL = 'DELETE_ADDRESS_FAIL';

export const ADDRESS_LIST_SUCCESS = 'ADDRESS_LIST_SUCCESS';
export const ADDRESS_LIST_FAIL = 'ADDRESS_LIST_FAIL';

export const ADDRESS_TYPE_SUCCESS = 'ADDRESS_TYPE_SUCCESS';
export const ADDRESS_TYPE_FAIL = 'ADDRESS_TYPE_FAIL';

export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';

export const UPDATE_PUBLIC_PROFILE_SUCCESS = 'UPDATE_PUBLIC_PROFILE_SUCCESS';
export const UPDATE_PUBLIC_PROFILE_FAIL = 'UPDATE_PUBLIC_PROFILE_FAIL';

export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_FAIL = 'UPDATE_USER_PROFILE_FAIL';

export const PUBLIC_PROFILE_SUCCESS = 'PUBLIC_PROFILE_SUCCESS';
export const PUBLIC_PROFILE_FAIL = 'PUBLIC_PROFILE_FAIL';

export const STATE_LIST_SUCCESS = 'STATE_LIST_SUCCESS';
export const STATE_LIST_FAIL = 'STATE_LIST_FAIL';


export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';

export const SET_ACTIVE_ADDRESS = 'SET_ACTIVE_ADDRESS';
